Application:
  image: adguard/adguardhome:latest
  container_name: ADGUARD-APP-001
  hostname: ADGUARD-APP-001
  restart: always
  networks:
    FRONTEND:
  ports:
    - "53:53/udp"
    - "67:67/udp" 
    - "68:68/tcp" 
    - "68:68/udp" 
    - "80:80/tcp" 
    - "443:443/tcp" 
    - "853:853/tcp" 
    - "3000:3000/tcp" 
  volumes:
    - $DOCKERDIR/appdata/adguardhome/conf:/opt/adguardhome/conf
    - $DOCKERDIR/appdata/adguardhome/work:/opt/adguardhome/work
    - $DOCKERDIR/shared/certs/example.com:/certs # optional: if you have your own SSL certs